### ISSUE TITLE
setup exists when packer is not installed

### ISSUE THREAD

**Issue by RajatGoyal** [news-scraper/infrastructure#4]
in setup script you have `set -e` at top
 
from `help set`:
  -e  Exit immediately if a command exits with a non-zero status.

so when packer is not installed, the program exists

```
brew list | grep -q packer
  if [ $? == '1' ]; then
    echo "Installing packer"
    brew install packer
  fi
```

**Comment by jules2689** [comment]
I removed the `set -e` in https://github.com/news-scraper/infrastructure/commit/4c8ce153697fea680f2a62d82d593f824b921ab2
Hope that helped.
